CREATE TABLE IF NOT EXISTS auto_user (
  id SERIAL PRIMARY KEY,
  login VARCHAR NOT NULL UNIQUE,
  password VARCHAR NOT NULL
);

CREATE TABLE IF NOT EXISTS auto_post (
  id SERIAL PRIMARY KEY,
  text VARCHAR,
  created TIMESTAMP WITHOUT TIME ZONE DEFAULT now(),
  user_id INT NOT NULL REFERENCES auto_user (id)
);